// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 
export const useGetEventsKey = "GetEvents";
export const UseGetEventsKeyFn = (clientOptions = {}, queryKey) => [useGetEventsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const useGetEventsByIdKey = "GetEventsById";
export const UseGetEventsByIdKeyFn = (clientOptions = {}, queryKey) => [useGetEventsByIdKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const useGetUsersKey = "GetUsers";
export const UseGetUsersKeyFn = (clientOptions = {}, queryKey) => [useGetUsersKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const useGetUsersByIdKey = "GetUsersById";
export const UseGetUsersByIdKeyFn = (clientOptions = {}, queryKey) => [useGetUsersByIdKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const useGetUsersByIdEventsKey = "GetUsersByIdEvents";
export const UseGetUsersByIdEventsKeyFn = (clientOptions = {}, queryKey) => [useGetUsersByIdEventsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const useGetUsersByIdParticipationsKey = "GetUsersByIdParticipations";
export const UseGetUsersByIdParticipationsKeyFn = (clientOptions = {}, queryKey) => [useGetUsersByIdParticipationsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const useGetUsersByIdSubscriptionsKey = "GetUsersByIdSubscriptions";
export const UseGetUsersByIdSubscriptionsKeyFn = (clientOptions = {}, queryKey) => [useGetUsersByIdSubscriptionsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const usePostAuthRegisterKey = "PostAuthRegister";
export const UsePostAuthRegisterKeyFn = (mutationKey) => [usePostAuthRegisterKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const usePostAuthLoginKey = "PostAuthLogin";
export const UsePostAuthLoginKeyFn = (mutationKey) => [usePostAuthLoginKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const usePostEventsKey = "PostEvents";
export const UsePostEventsKeyFn = (mutationKey) => [usePostEventsKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const usePostEventsByEventIdByUserIdKey = "PostEventsByEventIdByUserId";
export const UsePostEventsByEventIdByUserIdKeyFn = (mutationKey) => [usePostEventsByEventIdByUserIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const usePatchEventsByIdKey = "PatchEventsById";
export const UsePatchEventsByIdKeyFn = (mutationKey) => [usePatchEventsByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const usePatchUsersByIdKey = "PatchUsersById";
export const UsePatchUsersByIdKeyFn = (mutationKey) => [usePatchUsersByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const useDeleteEventsByIdKey = "DeleteEventsById";
export const UseDeleteEventsByIdKeyFn = (mutationKey) => [useDeleteEventsByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const useDeleteEventsByEventIdByUserIdKey = "DeleteEventsByEventIdByUserId";
export const UseDeleteEventsByEventIdByUserIdKeyFn = (mutationKey) => [useDeleteEventsByEventIdByUserIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const useDeleteUsersByIdKey = "DeleteUsersById";
export const UseDeleteUsersByIdKeyFn = (mutationKey) => [useDeleteUsersByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
export const UseGetMessagesByEventIdKey = "GetMessagesByEventId";
export const UseGetMessagesByEventIdKeyFn = (clientOptions = {}, queryKey) => [UseGetMessagesByEventIdKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
export const UsePostMessagesByEventIdKey = "PostMessagesByEventId";
export const UsePostMessagesByEventIdKeyFn = (mutationKey) => [UsePostMessagesByEventIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];