"use strict";
// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 
Object.defineProperty(exports, "__esModule", { value: true });
exports.UseDeleteUsersByIdKeyFn = exports.useDeleteUsersByIdKey = exports.UseDeleteEventsByEventIdByUserIdKeyFn = exports.useDeleteEventsByEventIdByUserIdKey = exports.UseDeleteEventsByIdKeyFn = exports.useDeleteEventsByIdKey = exports.UsePatchUsersByIdKeyFn = exports.usePatchUsersByIdKey = exports.UsePatchEventsByIdKeyFn = exports.usePatchEventsByIdKey = exports.UsePostEventsByEventIdByUserIdKeyFn = exports.usePostEventsByEventIdByUserIdKey = exports.UsePostEventsKeyFn = exports.usePostEventsKey = exports.UsePostAuthLoginKeyFn = exports.usePostAuthLoginKey = exports.UsePostAuthRegisterKeyFn = exports.usePostAuthRegisterKey = exports.UseGetUsersByIdSubscriptionsKeyFn = exports.useGetUsersByIdSubscriptionsKey = exports.UseGetUsersByIdParticipationsKeyFn = exports.useGetUsersByIdParticipationsKey = exports.UseGetUsersByIdEventsKeyFn = exports.useGetUsersByIdEventsKey = exports.UseGetUsersByIdKeyFn = exports.useGetUsersByIdKey = exports.UseGetUsersKeyFn = exports.useGetUsersKey = exports.UseGetEventsByIdKeyFn = exports.useGetEventsByIdKey = exports.UseGetEventsKeyFn = exports.useGetEventsKey = void 0;
exports.useGetEventsKey = "GetEvents";
const UseGetEventsKeyFn = (clientOptions = {}, queryKey) => [exports.useGetEventsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetEventsKeyFn = UseGetEventsKeyFn;
exports.useGetEventsByIdKey = "GetEventsById";
const UseGetEventsByIdKeyFn = (clientOptions = {}, queryKey) => [exports.useGetEventsByIdKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetEventsByIdKeyFn = UseGetEventsByIdKeyFn;
exports.useGetUsersKey = "GetUsers";
const UseGetUsersKeyFn = (clientOptions = {}, queryKey) => [exports.useGetUsersKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetUsersKeyFn = UseGetUsersKeyFn;
exports.useGetUsersByIdKey = "GetUsersById";
const UseGetUsersByIdKeyFn = (clientOptions = {}, queryKey) => [exports.useGetUsersByIdKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetUsersByIdKeyFn = UseGetUsersByIdKeyFn;
exports.useGetUsersByIdEventsKey = "GetUsersByIdEvents";
const UseGetUsersByIdEventsKeyFn = (clientOptions = {}, queryKey) => [exports.useGetUsersByIdEventsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetUsersByIdEventsKeyFn = UseGetUsersByIdEventsKeyFn;
exports.useGetUsersByIdParticipationsKey = "GetUsersByIdParticipations";
const UseGetUsersByIdParticipationsKeyFn = (clientOptions = {}, queryKey) => [exports.useGetUsersByIdParticipationsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetUsersByIdParticipationsKeyFn = UseGetUsersByIdParticipationsKeyFn;
exports.useGetUsersByIdSubscriptionsKey = "GetUsersByIdSubscriptions";
const UseGetUsersByIdSubscriptionsKeyFn = (clientOptions = {}, queryKey) => [exports.useGetUsersByIdSubscriptionsKey, ...(queryKey !== null && queryKey !== void 0 ? queryKey : [clientOptions])];
exports.UseGetUsersByIdSubscriptionsKeyFn = UseGetUsersByIdSubscriptionsKeyFn;
exports.usePostAuthRegisterKey = "PostAuthRegister";
const UsePostAuthRegisterKeyFn = (mutationKey) => [exports.usePostAuthRegisterKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UsePostAuthRegisterKeyFn = UsePostAuthRegisterKeyFn;
exports.usePostAuthLoginKey = "PostAuthLogin";
const UsePostAuthLoginKeyFn = (mutationKey) => [exports.usePostAuthLoginKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UsePostAuthLoginKeyFn = UsePostAuthLoginKeyFn;
exports.usePostEventsKey = "PostEvents";
const UsePostEventsKeyFn = (mutationKey) => [exports.usePostEventsKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UsePostEventsKeyFn = UsePostEventsKeyFn;
exports.usePostEventsByEventIdByUserIdKey = "PostEventsByEventIdByUserId";
const UsePostEventsByEventIdByUserIdKeyFn = (mutationKey) => [exports.usePostEventsByEventIdByUserIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UsePostEventsByEventIdByUserIdKeyFn = UsePostEventsByEventIdByUserIdKeyFn;
exports.usePatchEventsByIdKey = "PatchEventsById";
const UsePatchEventsByIdKeyFn = (mutationKey) => [exports.usePatchEventsByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UsePatchEventsByIdKeyFn = UsePatchEventsByIdKeyFn;
exports.usePatchUsersByIdKey = "PatchUsersById";
const UsePatchUsersByIdKeyFn = (mutationKey) => [exports.usePatchUsersByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UsePatchUsersByIdKeyFn = UsePatchUsersByIdKeyFn;
exports.useDeleteEventsByIdKey = "DeleteEventsById";
const UseDeleteEventsByIdKeyFn = (mutationKey) => [exports.useDeleteEventsByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UseDeleteEventsByIdKeyFn = UseDeleteEventsByIdKeyFn;
exports.useDeleteEventsByEventIdByUserIdKey = "DeleteEventsByEventIdByUserId";
const UseDeleteEventsByEventIdByUserIdKeyFn = (mutationKey) => [exports.useDeleteEventsByEventIdByUserIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UseDeleteEventsByEventIdByUserIdKeyFn = UseDeleteEventsByEventIdByUserIdKeyFn;
exports.useDeleteUsersByIdKey = "DeleteUsersById";
const UseDeleteUsersByIdKeyFn = (mutationKey) => [exports.useDeleteUsersByIdKey, ...(mutationKey !== null && mutationKey !== void 0 ? mutationKey : [])];
exports.UseDeleteUsersByIdKeyFn = UseDeleteUsersByIdKeyFn;
