/**
 * Generated by @openapi-codegen
 *
 * @version 1
 */
import * as reactQuery from "@tanstack/react-query";
import { useApiContext, ApiContext } from "./apiContext";
import type * as Fetcher from "./apiFetcher";
import { apiFetch } from "./apiFetcher";

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
