/**
 * Generated by @openapi-codegen
 *
 * @version 1
 */
export type User = {
  id: string;
  name: string;
  email: string;
  password?: string;
};

export type Event = {
  id: string;
  name: string;
  description: string;
  /**
   * @format date-time
   */
  date: string;
  location: string;
  /**
   * Link to the group
   */
  group?: string;
  /**
   * Link to the organizer
   */
  organizer: string;
};

export type Message = {
  id: string;
  /**
   * Link to the sender
   */
  sender: string;
  /**
   * Link to the event
   */
  event: string;
  /**
   * @format date-time
   */
  date: string;
  content: string;
};

export type Group = {
  id: string;
  name: string;
  description: string;
  /**
   * Link to the organizer
   */
  organizer: string;
};
