"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupSchema = exports.MessageSchema = exports.EventSchema = exports.UserSchema = void 0;
exports.UserSchema = {
    type: 'object',
    required: ['id', 'name', 'email'],
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
};
exports.EventSchema = {
    type: 'object',
    required: ['id', 'name', 'description', 'date', 'location', 'organizer'],
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        location: {
            type: 'string'
        },
        group: {
            type: 'string',
            description: 'Link to the group'
        },
        organizer: {
            type: 'string',
            description: 'Link to the organizer'
        }
    }
};
exports.MessageSchema = {
    type: 'object',
    required: ['id', 'sender', 'event', 'date', 'content'],
    properties: {
        id: {
            type: 'string'
        },
        sender: {
            type: 'string',
            description: 'Link to the sender'
        },
        event: {
            type: 'string',
            description: 'Link to the event'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        content: {
            type: 'string'
        }
    }
};
exports.GroupSchema = {
    type: 'object',
    required: ['id', 'name', 'description', 'organizer'],
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        organizer: {
            type: 'string',
            description: 'Link to the organizer'
        }
    }
};
