// This file is auto-generated by @hey-api/openapi-ts
import { createClient, createConfig } from '@hey-api/client-fetch';
export const client = createClient(createConfig());
/**
 * Creates and registers a new user
 */
export const postAuthRegister = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).post(Object.assign(Object.assign({}, options), { url: '/auth/register' }));
};
/**
 * Gives the JWT token to users with credentials
 */
export const postAuthLogin = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).post(Object.assign(Object.assign({}, options), { url: '/auth/login' }));
};
/**
 * Create a new event
 */
export const postEvents = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).post(Object.assign(Object.assign({}, options), { url: '/events' }));
};
/**
 * Get all events
 */
export const getEvents = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/events' }));
};
/**
 * Get an event by ID
 */
export const getEventsById = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/events/{id}' }));
};
/**
 * Delete an event by ID
 */
export const deleteEventsById = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).delete(Object.assign(Object.assign({}, options), { url: '/events/{id}' }));
};
/**
 * Update an event by ID
 */
export const patchEventsById = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).patch(Object.assign(Object.assign({}, options), { url: '/events/{id}' }));
};
/**
 * Add a user to an event
 * Allows a user to join an event by adding their user ID to the event's attendees.
 */
export const postEventsByEventIdByUserId = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).post(Object.assign(Object.assign({}, options), { url: '/events/{eventId}/{userId}' }));
};
/**
 * Remove a user from an event
 * Allows removal of a user from an event's attendees by user ID.
 */
export const deleteEventsByEventIdByUserId = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).delete(Object.assign(Object.assign({}, options), { url: '/events/{eventId}/{userId}' }));
};
/**
 * Get all users
 */
export const getUsers = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/users' }));
};
/**
 * Get a user by ID
 */
export const getUsersById = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/users/{id}' }));
};
/**
 * Delete a user by ID
 */
export const deleteUsersById = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).delete(Object.assign(Object.assign({}, options), { url: '/users/{id}' }));
};
/**
 * Update a user by ID
 */
export const patchUsersById = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).patch(Object.assign(Object.assign({}, options), { url: '/users/{id}' }));
};
/**
 * Get all events organized by a user
 */
export const getUsersByIdEvents = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/users/{id}/events' }));
};
/**
 * Get all events where a user has participated
 */
export const getUsersByIdParticipations = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/users/{id}/participations' }));
};
/**
 * Get all events at which a user is subscribed
 */
export const getUsersByIdSubscriptions = (options) => {
    var _a;
    return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : client).get(Object.assign(Object.assign({}, options), { url: '/users/{id}/subscriptions' }));
};
