"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultService = void 0;
const OpenAPI_1 = require("./core/OpenAPI");
const request_1 = require("./core/request");
class DefaultService {
    /**
     * Creates and registers a new user
     * @param data The data for the request.
     * @param data.requestBody
     * @returns User User registered
     * @throws ApiError
     */
    static postAuthRegister(data = {}) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'POST',
            url: '/auth/register',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    /**
     * Gives the JWT token to users with credentials
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Login completed
     * @throws ApiError
     */
    static postAuthLogin(data = {}) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'POST',
            url: '/auth/login',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    /**
     * Create a new event
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Event Event created
     * @throws ApiError
     */
    static postEvents(data = {}) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'POST',
            url: '/events',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    /**
     * Get all events
     * @returns Event List of events
     * @throws ApiError
     */
    static getEvents() {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/events'
        });
    }
    /**
     * Get an event by ID
     * @param data The data for the request.
     * @param data.id
     * @returns Event Event found
     * @throws ApiError
     */
    static getEventsById(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/events/{id}',
            path: {
                id: data.id
            },
            errors: {
                404: 'Event not found'
            }
        });
    }
    /**
     * Delete an event by ID
     * @param data The data for the request.
     * @param data.id
     * @returns void Event deleted
     * @throws ApiError
     */
    static deleteEventsById(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'DELETE',
            url: '/events/{id}',
            path: {
                id: data.id
            },
            errors: {
                404: 'Event not found'
            }
        });
    }
    /**
     * Update an event by ID
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns Event Event updated
     * @throws ApiError
     */
    static patchEventsById(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'PATCH',
            url: '/events/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    /**
     * Add a user to an event
     * Allows a user to join an event by adding their user ID to the event's attendees.
     * @param data The data for the request.
     * @param data.eventId The ID of the event to join.
     * @param data.userId The ID of the user joining the event.
     * @returns unknown Successfully added user to event
     * @throws ApiError
     */
    static postEventsByEventIdByUserId(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'POST',
            url: '/events/{eventId}/{userId}',
            path: {
                eventId: data.eventId,
                userId: data.userId
            },
            errors: {
                404: 'Event not found'
            }
        });
    }
    /**
     * Remove a user from an event
     * Allows removal of a user from an event's attendees by user ID.
     * @param data The data for the request.
     * @param data.eventId The ID of the event from which to remove the user.
     * @param data.userId The ID of the user to be removed from the event.
     * @returns unknown Successfully removed user from event
     * @throws ApiError
     */
    static deleteEventsByEventIdByUserId(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'DELETE',
            url: '/events/{eventId}/{userId}',
            path: {
                eventId: data.eventId,
                userId: data.userId
            },
            errors: {
                404: 'Event or user not found',
                500: 'Server error'
            }
        });
    }
    /**
     * Get all users
     * @returns User List of users
     * @throws ApiError
     */
    static getUsers() {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/users'
        });
    }
    /**
     * Get a user by ID
     * @param data The data for the request.
     * @param data.id
     * @returns User User found
     * @throws ApiError
     */
    static getUsersById(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/users/{id}',
            path: {
                id: data.id
            },
            errors: {
                404: 'User not found'
            }
        });
    }
    /**
     * Delete a user by ID
     * @param data The data for the request.
     * @param data.id
     * @returns void User deleted
     * @throws ApiError
     */
    static deleteUsersById(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'DELETE',
            url: '/users/{id}',
            path: {
                id: data.id
            },
            errors: {
                404: 'User not found'
            }
        });
    }
    /**
     * Update a user by ID
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns User User updated
     * @throws ApiError
     */
    static patchUsersById(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'PATCH',
            url: '/users/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    /**
     * Get all events organized by a user
     * @param data The data for the request.
     * @param data.id
     * @returns Event List of events
     * @throws ApiError
     */
    static getUsersByIdEvents(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/users/{id}/events',
            path: {
                id: data.id
            }
        });
    }
    /**
     * Get all events where a user has participated
     * @param data The data for the request.
     * @param data.id
     * @returns Event List of events
     * @throws ApiError
     */
    static getUsersByIdParticipations(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/users/{id}/participations',
            path: {
                id: data.id
            }
        });
    }
    /**
     * Get all events at which a user is subscribed
     * @param data The data for the request.
     * @param data.id
     * @returns Event List of events
     * @throws ApiError
     */
    static getUsersByIdSubscriptions(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: 'GET',
            url: '/users/{id}/subscriptions',
            path: {
                id: data.id
            }
        });
    }
}
exports.DefaultService = DefaultService;
